### ISSUE TITLE
link checker fails with config issue

### ISSUE THREAD

**Issue by ligi** [efdevcon/DIPs#20]
This happens on PR #19

```
Run gaurav-nelson/github-action-markdown-link-check@v1
..
added 66 packages from 72 contributors in 3.682s
USE_QUIET_MODE: yes
USE_VERBOSE_MODE: yes
FOLDER_PATH: .
MAX_DEPTH: -1
CHECK_MODIFIED_FILES: yes
FILE_EXTENSION: .md
BASE_BRANCH: master
From https://github.com/efdevcon/DIPs
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
Cannot find mlc_config.json
NOTE: See https://github.com/tcort/markdown-link-check#config-file-format to know more about
customizing markdown-link-check by using a configuration file.
=========================> MARKDOWN LINK CHECK <=========================

ERROR: File not found! Please provide a vaild filename as an argument.

FILE: DIPs/POAP-DIP.md

1 links checked.

=========================================================================
```

but if I read the README in @gaurav-nelson 's repo correctly - this file should be optional (only if you want to do something special) 

fun-fact: just saw that this project is [treeware](https://ecologi.com/treeware) - nice concept - cc @raphabenoi @vrde

**Comment by gaurav-nelson** [comment]
Thanks for tagging me, you just discovered an issue with the `check-modified-files-only` logic. Currently it looks for all changed markdown files and its failing for the deleted `DIPs/DIP-0.md` file in your PR. I'll create a new issue at https://github.com/gaurav-nelson/github-action-markdown-link-check and fix it.

**Comment by ligi** [comment]
@gaurav-nelson thanks!

**Comment by gaurav-nelson** [comment]
This should be fixed now, try to re-run the workflow.

**Comment by ligi** [comment]
great - looks good now - thanks for the fast fix!
