### ISSUE TITLE
list of attendees crypto keys

### ISSUE THREAD

**Issue by barryWhiteHat** [efdevcon/DIPs#45]
I would love to see a bunch of devcon apps. But to do this we need to get a list of all attendees crypto keys. Is this info collected and shared?

**Comment by ligi** [comment]
DIP-5.md (Status KeyCards) might be of help here (also wondering if having so many cards could somehow help the HardwareNotes project and if there could be a DIP build on it)
Also DIP-6.md (AlphaWallet Ticket attestations) can be used to build devcon apps.
Very curious what you have in mind!

**Comment by guylouis** [comment]
Keycard indeed come with two applets:
- **one is a hardware wallet**, it is integrated with Status in a very secure fashion. It needs to be paired with the phone, any tx needs a PIN to be entered to be signed, it can generate a random wallet or import one. 
- **one is a simpler applet, called keycard Cash, that has a lower security profile.** It generates the key randomly once for all, does not need any pairing with the phone, does not need a PIN to be entered to sign a tx. It signs any transaction that's presented over NFC to the card. It's great to prove a user has been physically at a particular place, or sign a meta-tx for a smart contract wallet. Moreover any dApp can use Keycard web3 API  https://keycard.tech/docs/web3.html, to ask the card tapped on the browser (Status for instance) to sign a tx. 

The list of public keys for Keycard Cash could be made public before Devcon, making them a pseudo-anonymous way to identify devcon attendees at Devcon with any dApp.

**Comment by Thajuiceman69** [comment]
Good work from everyone involved!
